# @package _global_
agent:
  name: opt_ail
  _target_: agent.opt_ail.OPT_AIL
  obs_dim: ??? # to be specified later
  action_dim: ??? # to be specified later

  critic_cfg: ${q_net}
  actor_cfg: ${diag_gaussian_actor}
  disc_cfg: ${disc_net}
  init_temp: 1e-2 # use a low temp for IL

  alpha_lr: 3e-4
  alpha_betas: [0.9, 0.999]

  actor_lr: 3e-5
  actor_betas: [0.9, 0.999]
  actor_update_frequency: 1

  disc_lr: 3e-5
  disc_betas: [0.9, 0.999]
  disc_update_frequency: 1

  critic_lr: 3e-4
  critic_betas: [0.9, 0.999]
  critic_tau: 0.005
  critic_target_update_frequency: 1

  # learn temperature coefficient (disabled by default)
  learn_temp: false
  update_per_step: 1

  # Use either value_dice actor or normal SAC actor loss
  vdice_actor: false

q_net:
  _target_: module.critic.SingleQCritic
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
  hidden_dim: 256
  hidden_depth: 2

disc_net:
  _target_: module.discriminator.Discriminator
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
  hidden_dim: 256
  hidden_depth: 2

diag_gaussian_actor:
  _target_: module.actor.DiagGaussianActor
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
  hidden_dim: 256
  hidden_depth: 2
  log_std_bounds: [-5, 2]